
from numpy import ndarray
from rope.version import get_version
from rope.io.blueprint_reader import parse_header

def output_pdb(line:str,seq:str,index:int,line_index:int,align_residue:ndarray,atom_count:int,residue_count:int) -> str:
    line_string = list(line)
    line_string[6:11] = f"{atom_count:5d}"
    line_string[17:20] = f"{seq[index]:>3s}"
    line_string[22:26] = f"{residue_count:4d}"
    line_string[30:38] = f"{align_residue[line_index][0]:8.3f}"
    line_string[38:46] = f"{align_residue[line_index][1]:8.3f}"
    line_string[46:54] = f"{align_residue[line_index][2]:8.3f}"
    return "".join(line_string)

def output_ligand_pdb(line:str,align_atom:ndarray,ligand_index:int,atom_count:int):
    line_string = list(line)
    line_string[6:11] = f"{atom_count:5d}"
    line_string[22:26] = f"{ligand_index:4d}"
    line_string[30:38] = f"{align_atom[0]:8.3f}"
    line_string[38:46] = f"{align_atom[1]:8.3f}"
    line_string[46:54] = f"{align_atom[2]:8.3f}"
    return "".join(line_string)

def get_remarks(file,ligands:dict):
    remarks = []
    remarks.append(f"REMARK Generated by ROPE version {get_version()}\n")
    remarks.append(f"REMARK Generated from {parse_header(file)[0]}\n")
    remarks.append(f"REMARK Ligand variants:\n")
    for i in ligands:
        remarks.append(f"REMARK {i} = {ligands[i]}\n")
    return remarks